include_directories(BEFORE ..)

if( "${CMAKE_SYSTEM_NAME}" STREQUAL "HP-UX" )
  add_definitions( -Wall -fPIC -g -D_REENTRANT -DACE_HAS_AIO_CALLS -D_GNU_SOURCE -DACE_NO_INLINE -DACE_HAS_LINUX_NPTL -mlp64 -D_PSTAT64)
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_PSTAT64 -mlp64")
else()
  add_definitions( -Wall -fPIC -g -O0 -D_REENTRANT -DACE_HAS_AIO_CALLS -D_GNU_SOURCE -DACE_NO_INLINE -DACE_HAS_LINUX_NPTL)
endif()


