#ifndef MY_ICE
#define MY_ICE

module demo
{

/*

  void func(string msg, long time);
  long sayBye (string msg, float time, out string bye);
*/

struct package
{
  string str1;
  long length;
  short op;
};  

sequence<package> MsgSeq;

struct MyStruct
{
  MsgSeq abc;
  string str;
};

class A
{
  string getV ();
};

//local class A;

class MyHello
{
  ["ami"] string sayHello(string msg, short u, out long v, out short sval);

  ["amd"] string sayBye(string msg, short u, out long v);

  ["ami","amd"] long testHello(long v1, short v2, float v3, out double v4, out string v5);
  
  long testSeq (MyStruct cd, out long lvalue);
  
  //long setA (A theA);
};


};

#endif
