
CPPFLAGS+=-I../../.. -I./  -g -DAIX -D_REENTRANT -DACE_HAS_AIO_CALLS -D_GNU_SOURCE -DACE_NO_INLINE 
LDFLAGS+=-L../../../lib -Wl,-brtl -lpthread -lrt -licc -licm -licmmsg

all: testPub

testPub: testPub.o javatopic.o TvmEvent.o
	g++ $(LDFLAGS) -o testPub testPub.o javatopic.o TvmEvent.o 


%.o : %.cpp
	g++ $(CPPFLAGS) -c $< -o $@

clean:
	rm -rf *.o testPub
