
CPPFLAGS+=-I../../.. -I./  -g -DHPUX -D_REENTRANT -DACE_HAS_AIO_CALLS -D_GNU_SOURCE -DACE_NO_INLINE -DACE_HAS_LINUX_NPTL
LDFLAGS+=-L../../../lib -lpthread -lrt -licc -licm -licmmsg

all: testPub

testPub: testPub.o javatopic.o
	g++ $(LDFLAGS) -o testPub testPub.o javatopic.o


%.o : %.cpp
	g++ $(CPPFLAGS) -c $< -o $@

clean:
	rm -rf *.o testPub
